import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from 'sonner'

const myFont = localFont({
  src: '../public/fonts/Parastoo-VariableFont_wght.ttf',
})
const vazirFont = localFont({
  src: '../public/fonts/Vazirmatn-VariableFont_wght.ttf',
})

export const numericFont = localFont({
  src: '../public/fonts/FarsiAdad.woff2',
  variable: '--font-adad',
})

export const metadata: Metadata = {
  title: 'Leather shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`  ${myFont.className}  adad  antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
