import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from 'sonner'

const myFont = localFont({
  src: '../public/fonts/Parastoo-VariableFont_wght.ttf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className}   antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
